prometheus:
  image: prom/prometheus
  container_name: Prometheus
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./prometheus:/var/lib/prometheus
    - ./rules.yml:/etc/prometheus/rules.yml
  command:
    - '--config.file=/etc/prometheus/prometheus.yml'
  ports:
  - 9090:9090
  restart: unless-stopped

grafana:
  image: grafana/grafana
  container_name: Grafana
  volumes:
    - ./grafana:/var/lib/grafana
    - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
  ports:
  - 3000:3000
  restart: unless-stopped

alertmanager:
  image: prom/alertmanager
  container_name: Alertmanager
  volumes:
    - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    - ./alertmanager:/var/lib/alertmanager
  command:
    - '--config.file=/etc/alertmanager/alertmanager.yml'
  ports:
  - 9093:9093
  restart: unless-stopped